version: '3'

volumes:
  postgres-data:

services:
  web:
    container_name: "web"
    build: ./
    working_dir: /code/bakerydemo
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
      - ./bakerydemo:/code/bakerydemo:delegated,rw
    ports:
      - "9000:8000"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@db/wagtail
      PYTHONPATH: /code/wagtail:/code/bakerydemo:$PYTHONPATH
    depends_on:
      - db
      - frontend

  db:
    container_name: "db"
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"

  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /code/wagtail
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
    command:
      - /bin/sh
      - -c
      - |
        cp -ru /node_modules /code/wagtail
        npm run start

  # CNK run another web site leveraging the db and mounted wagtail source code
  tutorial:
    container_name: "tutorial"
    build:
      context: .
      dockerfile: Dockerfile.tutorial
    working_dir: /code/tutorial
    command: ./manage.py runserver 0.0.0.0:8787
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
      - ./tutorial:/code/tutorial:delegated,rw
    ports:
      - "8787:8787"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@db/tutorial
      PYTHONPATH: /code/wagtail:/code/tutorial:$PYTHONPATH
    depends_on:
      - db
      - frontend
