version: '3'

volumes:
  postgres-data:
  mysql-data:

services:
  web:
    container_name: "web"
    build: ./
    working_dir: /code/bakerydemo
    command: ./manage.py runserver 0.0.0.0:8000
    restart: "no"
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
      - ./bakerydemo:/code/bakerydemo:delegated,rw
    ports:
      - "9000:8000"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@db/wagtail
      PYTHONPATH: /code/wagtail:/code/bakerydemo:$PYTHONPATH
    depends_on:
      - db
      - frontend

  db:
    container_name: "db"
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: "no"
    expose:
      - "5432"

  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /code/wagtail
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
    command:
      - /bin/sh
      - -c
      - |
        cp -ru /node_modules /code/wagtail
        npm run start
    restart: "no"


  # mysql:
  #   container_name: "tutorial-db"
  #   image: mysql:8.0.25
  #   # Using the older auth because Debian's default-mysql-client throws error without it
  #   # (2061, 'RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support')
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_USER: wagtail
  #     MYSQL_PASSWORD: changeme
  #     MYSQL_DATABASE: tutorial
  #   cap_add:
  #     - SYS_NICE  # removes error messages like: db-oof | mbind: Operation not
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  # CNK run another web site leveraging the db and mounted wagtail source code
  tutorial:
    container_name: "tutorial"
    build:
      context: .
      dockerfile: Dockerfile.tutorial
    working_dir: /code/tutorial
    command: ./manage.py runserver 0.0.0.0:8787
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
      - ./tutorial:/code/tutorial:delegated,rw
    ports:
      - "8787:8787"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@db/tutorial
      # DATABASE_URL: mysql://wagtail:changeme@tutorial-db/tutorial
      PYTHONPATH: /code/wagtail:/code/tutorial:$PYTHONPATH
    depends_on:
      - db
      # - mysql
      - frontend
